<?xml version="1.0" encoding="utf-8"?>
<TestRun id="f3b2f750-07db-412d-a1ec-54899ba68997" name="@bekk-mac-2296 2023-08-15 13:09:16" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-08-15T13:09:16.8568180+02:00" queuing="2023-08-15T13:09:16.8568180+02:00" start="2023-08-15T13:09:11.2955380+02:00" finish="2023-08-15T13:09:16.8700000+02:00" />
  <TestSettings name="default" id="6aa286ee-874e-431e-be4e-1a14a187a3fa">
    <Deployment runDeploymentRoot="_bekk-mac-2296_2023-08-15_13_09_16" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="7822e094-0a86-42ca-865e-34c50745585d" testId="bd0b13f5-8a4f-ce07-23eb-d6f5a2bd3fe4" testName="Tests.GetEvent.GetEvent.Authenticated users can get participations for participant" computerName="bekk-mac-2296" duration="00:00:00.0010000" startTime="2023-08-15T13:09:16.6471350+02:00" endTime="2023-08-15T13:09:16.6471860+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="7822e094-0a86-42ca-865e-34c50745585d">
      <Output>
        <ErrorInfo>
          <Message>System.AggregateException : One or more errors occurred. (An error occurred trying to start process 'podman' with working directory '/Users/ole/Bekk/bekkno/bekk-arrangement-svc/Tests/bin/Debug/net7.0'. No such file or directory) (The following constructor parameters did not have matching fixture data: DatabaseFixture fixture)
---- System.ComponentModel.Win32Exception : An error occurred trying to start process 'podman' with working directory '/Users/ole/Bekk/bekkno/bekk-arrangement-svc/Tests/bin/Debug/net7.0'. No such file or directory
---- The following constructor parameters did not have matching fixture data: DatabaseFixture fixture</Message>
          <StackTrace>
----- Inner Stack Trace #1 (System.ComponentModel.Win32Exception) -----
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32&amp; stdinFd, Int32&amp; stdoutFd, Int32&amp; stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Fli.Command.startProcess(FSharpFunc`2 inputFunc, FSharpFunc`2 outputFunc, ProcessStartInfo psi)
   at Fli.Command.Command.execute(ExecContext context)
   at Container.runCLI[a](a arguments) in /Users/ole/Bekk/bekkno/bekk-arrangement-svc/Tests/Utils/Container.fs:line 24
   at Container.containerExists() in /Users/ole/Bekk/bekkno/bekk-arrangement-svc/Tests/Utils/Container.fs:line 35
   at Tests.DatabaseFixture..ctor() in /Users/ole/Bekk/bekkno/bekk-arrangement-svc/Tests/Fixture.fs:line 18
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tests.GetEvent.GetEvent.Authenticated users can get participations for participant" storage="/users/ole/bekk/bekkno/bekk-arrangement-svc/tests/bin/debug/net7.0/tests.dll" id="bd0b13f5-8a4f-ce07-23eb-d6f5a2bd3fe4">
      <Execution id="7822e094-0a86-42ca-865e-34c50745585d" />
      <TestMethod codeBase="/Users/ole/Bekk/bekkno/bekk-arrangement-svc/Tests/bin/Debug/net7.0/Tests.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tests.GetEvent.GetEvent" name="Authenticated users can get participations for participant" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="bd0b13f5-8a4f-ce07-23eb-d6f5a2bd3fe4" executionId="7822e094-0a86-42ca-865e-34c50745585d" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit .NET 7.0.10)
[xUnit.net 00:00:03.95]   Discovering: Tests
[xUnit.net 00:00:04.04]   Discovered:  Tests
[xUnit.net 00:00:04.05]   Starting:    Tests
[xUnit.net 00:00:04.17]       System.AggregateException : One or more errors occurred. (An error occurred trying to start process 'podman' with working directory '/Users/ole/Bekk/bekkno/bekk-arrangement-svc/Tests/bin/Debug/net7.0'. No such file or directory) (The following constructor parameters did not have matching fixture data: DatabaseFixture fixture)
[xUnit.net 00:00:04.17]       ---- System.ComponentModel.Win32Exception : An error occurred trying to start process 'podman' with working directory '/Users/ole/Bekk/bekkno/bekk-arrangement-svc/Tests/bin/Debug/net7.0'. No such file or directory
[xUnit.net 00:00:04.17]       ---- The following constructor parameters did not have matching fixture data: DatabaseFixture fixture
[xUnit.net 00:00:04.17]       Stack Trace:
[xUnit.net 00:00:04.17]         
[xUnit.net 00:00:04.17]         ----- Inner Stack Trace #1 (System.ComponentModel.Win32Exception) -----
[xUnit.net 00:00:04.17]            at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32&amp; stdinFd, Int32&amp; stdoutFd, Int32&amp; stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
[xUnit.net 00:00:04.17]            at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
[xUnit.net 00:00:04.17]            at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
[xUnit.net 00:00:04.17]            at Fli.Command.startProcess(FSharpFunc`2 inputFunc, FSharpFunc`2 outputFunc, ProcessStartInfo psi)
[xUnit.net 00:00:04.17]            at Fli.Command.Command.execute(ExecContext context)
[xUnit.net 00:00:04.17]         /Users/ole/Bekk/bekkno/bekk-arrangement-svc/Tests/Utils/Container.fs(24,0): at Container.runCLI[a](a arguments)
[xUnit.net 00:00:04.17]         /Users/ole/Bekk/bekkno/bekk-arrangement-svc/Tests/Utils/Container.fs(35,0): at Container.containerExists()
[xUnit.net 00:00:04.17]         /Users/ole/Bekk/bekkno/bekk-arrangement-svc/Tests/Fixture.fs(18,0): at Tests.DatabaseFixture..ctor()
[xUnit.net 00:00:04.17]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
[xUnit.net 00:00:04.17]            at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[xUnit.net 00:00:04.17]         ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
[xUnit.net 00:00:04.17]         
[xUnit.net 00:00:04.18]   Finished:    Tests
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="bekk-mac-2296" outcome="Error" timestamp="2023-08-15T13:09:16.6596360+02:00">
        <Text>[xUnit.net 00:00:04.17]     Tests.GetEvent.GetEvent.Authenticated users can get participations for participant [FAIL]</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>